### ISSUE TITLE
CTRL + S doesn't save... 

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#10]
The most basic shot-cut key doesn't work.

Also when closing a file, the error message isn't an error, it should be a warning.

![image](https://cloud.githubusercontent.com/assets/895629/6550112/58c03874-c65b-11e4-9464-62069ab75614.png)

**Comment by pauljz** [comment]
This is fixed in the latest CI build. The title is now "Save changes?" and Ctrl-S works again!
