### ISSUE TITLE
Canceling a rename file causes the button to stay

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#100]
![image](https://cloud.githubusercontent.com/assets/895629/6881735/34cf8432-d5a7-11e4-9e3f-7c877a5dfdf4.png)

Right Click file > Rename

Press Cancel

Don't move cursor away from button.

**Comment by stirno** [comment]
Marking fixed in dev because we're removing the context menus from these controls for now.. They will return in the future (likely at the same time we implement some of your feature suggestions).
