### ISSUE TITLE
Delete File from workspace doesn't do anything

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#101]
Tried deleting a file. Nothing happened. :)

Shouldn't have a button if not implemented yet. If it is, it's not working.

**Comment by stirno** [comment]
For me.. it works. I think its likely that it just ate an IO Exception when you attempted to delete. Needs some work regardless.

**Comment by stirno** [comment]
Marking fixed in dev because we're removing the context menus from these controls for now.. They will return in the future (likely at the same time we implement some of your feature suggestions).
