### ISSUE TITLE
Closing the IDE while its opening causes it to crash

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#103]
If its checking for updates when its closed, it causes it to crash.

![crashing](https://cloud.githubusercontent.com/assets/895629/6881994/1b243e88-d5b1-11e4-8092-df7f322cefed.gif)

**Comment by stirno** [comment]
Can no longer repro in dev but its not entirely clear why.. Going to mark fixed once we merge back in but might have to revisit.
