### ISSUE TITLE
Tabbing multiple lines can cause crash

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#104]
![more-tabbing-issues](https://cloud.githubusercontent.com/assets/895629/6882177/07dc326c-d5b7-11e4-849a-b761ceb979e3.gif)

Pasted in some text that had odd tabbing. 

Resetting the tabbing (shift tab) then re-tabbing, tabs the first line only. 

De-selecting then tabbing causes it to crash.

**Comment by pauljz** [comment]
We've cleaned the indent/unindent code up a bunch on the dev branch. Should be fixed for you once we've merged this back onto the CI channel
