### ISSUE TITLE
Short Cut Keys

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#105]
- [ ] Comment Selected Code (e.g, `CTRL` + `K`-`C`, or `CTRL` + `/`, etc)
  - [ ] Comment
  - [ ] Uncomment

**Comment by pauljz** [comment]
Since comments are language-specific, this ends up being a fairly big task.

We'll come up with an API for code engines/plugins to define the rules for how comments should be created and removed for individual languages.

Moved to the backlog: fluentCODE/ScrawlBacklog#14
