### ISSUE TITLE
Cursor in wrong spot after mouse left-click

### ISSUE THREAD

**Issue by miguelzakharia** [fluentCODE/ScrawlIssues#108]
Most of the time when I left-click in the editor, the cursor ends up being a few characters to the right of where it should be.

**Comment by pauljz** [comment]
Is this happening on a line that's indented with tab characters? I think our positioning code misses tabs in a few places. If so, this is fixed on our dev branch.

**Comment by miguelzakharia** [comment]
Yes, that's correct.

**Comment by JonBons** [comment]
I'm seeing something that I think is related to this but I'm not sure.

Opened XML file and the whole editor would go black except for the initially selected line, after a line was selected it would stop which I feel may be unrelated to this but I did see the caret behaving odd where it would blink between the currently selected line and the last selected line.

Video: https://dl.dropboxusercontent.com/u/1652088/ShareX/2015-04/2015-04-01_11-54-27_lf6Hc.webm
