### ISSUE TITLE
Previewed files don't become permanent on edit

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#11]
Clicking a file once puts the tab on the right hand side.

Double clicking puts it on the left.

I assume single click is like a 'preview' from Visual Studio. Except editing it doesn't put it to the left.

**Comment by pauljz** [comment]
Yeah, single click previews the file. We'll make it so editing the previewed file makes it a permanent tab.

**Comment by pauljz** [comment]
Fixed in build 212 https://twitter.com/scrawlcommits/status/575510236133486592
