### ISSUE TITLE
Sublime Style Command Window

### ISSUE THREAD

**Issue by xavierzwirtz** [fluentCODE/ScrawlIssues#111]
In Sublime Text, if you hit `Ctrl + Shift + P` you get a command dialog, giving you access to 
- Changing the language engine of the buffer
- Running extension commands
- General commands

Would be cool if scrawl supported this, it makes mouse free use a lot easier.

**Comment by xavierzwirtz** [comment]
![screenshot 2015-03-31 00 37 09](https://cloud.githubusercontent.com/assets/474343/6912943/98d531d2-d73e-11e4-9d3d-1bd260ac2fbc.png)

**Comment by stirno** [comment]
Agreed. definitely in our plans.. We actually had started on that in our prototype, just havent found our way back to it yet. 

![screen shot 2014-10-23 at 3 26 19 pm](https://cloud.githubusercontent.com/assets/666175/6912945/9bb21b5e-d73e-11e4-8aab-3f71eb209ce5.png)

**Comment by xavierzwirtz** [comment]
Oh wow, thats hot. In sublime, it also shows the key combo to press if the command is assigned to cursor keys. Would make it easy for the user to jump right into use, but learn the speedy ways to use scrawl.

**Comment by stirno** [comment]
Moved to backlog
