### ISSUE TITLE
Manually choose code engine

### ISSUE THREAD

**Issue by xavierzwirtz** [fluentCODE/ScrawlIssues#112]
Currently the code engine seems to be chosen based on the file extension. Would be handy to be able to manually select js, c#, f#. ect. Would allow you to 
- Start a new buffer
- Set the code engine to some engine with a built in repl
- Immediately start executing code in that repl

**Comment by pauljz** [comment]
We're planning to put this in the status bar, once we add it. Probably one of the first things we'll add once our current round of refactors is done.

(Although, adding the REPL will be a while still)

**Comment by stirno** [comment]
Moved to backlog
