### ISSUE TITLE
Allow community contributions to built in code engines

### ISSUE THREAD

**Issue by xavierzwirtz** [fluentCODE/ScrawlIssues#114]
I notice that there seems to be quite a few code engines already included with scrawl. It would be great both for allowing the community to contribute features, as well as jump start new code engines if the included code engines were 'open source'. I know there is a certain amount of special sauce, so if it were licensed with the GPL or AGPL scrawl would still have full commercial usage rights while allowing the community to fork and enhance to their hearts content.

**Comment by dpen2000** [comment]
If code engines are open sourced, I'd prefer it be under liberal licenses like MIT/APACHE especially if they are themselves depending on open source projects like Roslyn under these types of licenses.

**Comment by stirno** [comment]
There are two things in play here really... Most Syntax Highlighting is handled by tmLanguage files. We include a pretty decent number of these in Scrawl by default. They will be shared, with their respective licenses, in a fluentCODE repo at some point so we can take contributions/new files from the community.

Code Engines driven by the SDK are quite a bit more than that and generally including their own lexers or other important/heavy pieces. We will be releasing the TypeScript Code Engine for sure though I'm not certain on timeframe for that. Additionally Code Engines will be able to expose their own external APIs for plugins to interact with them directly which I think will fill the gaps for customization needs.

I do hope to be able to open source more around the Code Engines in the future but we just don't have time to take on running that as an OSS project right now.

**Comment by stirno** [comment]
We'll be putting the TypeScript code engine out there relatively soon and will continue this discussion on its repo. Closing for now, Thanks for the feedback!
