### ISSUE TITLE
Auto-inserted characters occurring in strings/comments

### ISSUE THREAD

**Issue by aarondandy** [fluentCODE/ScrawlIssues#117]
In a JS file when typing the following, Scrawl really wants to add in some extra quotes for me.

Example: Typing `// Poop.js, the coolest new framework you haven't heard of` will end up with an extra `'` at the end.

Example: When there is existing JS of `var thing = 'poop;` which is missing a `'` when I add the missing `'` in I get two instead of one.

**Comment by pauljz** [comment]
We'll probably fix this generically by just not auto-inserting characters in ranges that the lexer detects as strings or comments.

In some languages we'll want to have a subset that still occur, e.g. curly braces for string interpolation in Ruby or C#6, but that's an edge case that we can support later with code engines.

**Comment by stirno** [comment]
In the dev branch (that we'll be merging back real soon) we no longer insert inside strings/comments and the deletion logic is different.

**Comment by aarondandy** [comment]
:+1:
