### ISSUE TITLE
JS edits do not flag a file as changed

### ISSUE THREAD

**Issue by aarondandy** [fluentCODE/ScrawlIssues#118]
Open an _existing_ .js file containing the text `var someThing = ['po','op''];` (note the extra `'`) then place your cursor _before_ the first two quotes (`''`) and press the Delete key.

The UI does not flag the file as being edited and it will not save the change when pressing Ctrl+S.

**Comment by pauljz** [comment]
Looks like Delete doesn't trigger a dirty flag on the current build.

This is fixed on the dev build. Any action that manipulates text will flag as dirty now.
