### ISSUE TITLE
Crash when pressing ctrl+x with no selection

### ISSUE THREAD

**Issue by marshall007** [fluentCODE/ScrawlIssues#119]
With the cursor on a line and no text selected, hitting `ctrl+x` crashes the program. I'd expect this to cut the entire line similar to how SublimeText does it.

**Comment by pauljz** [comment]
The crash is fixed in the dev branch, but we're not handling cutting the line yet. I'll add that in pretty soon.

**Comment by pauljz** [comment]
Okay, in the dev branch, the Cut and Copy keybinds will now cut or copy the whole line a cursor is on if there is no selection.
