### ISSUE TITLE
Cannot use scroll wheel

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#12]
When in the file explorer. Scroll wheel doesn't move the view up or down.

**Comment by pauljz** [comment]
Yup, this is because Winforms only lets you mousewheel scroll the focused control, and those tree views never actually take focus. We'll need to manually forward the scroll events to the thing you're hovering, instead of using focus. Shouldn't be a big deal with our scrolling abstraction.

**Comment by pauljz** [comment]
Fixed in build 216 https://twitter.com/scrawlcommits/status/575525433749475331
