### ISSUE TITLE
Installer crashes before the splash screen

### ISSUE THREAD

**Issue by scottmeyer** [fluentCODE/ScrawlIssues#120]
When running the latest installer, it crashes immediately.

System Stats:
![image](https://cloud.githubusercontent.com/assets/523034/6972553/27c59c58-d94a-11e4-92c4-d9e91b19ccb4.png)

**Comment by pauljz** [comment]
Note that the app still installs correctly, and can be launched from the start menu. It's just the very first load after the install that fails/crashes.

**Comment by scottmeyer** [comment]
@pauljz acked and confirmed.

**Comment by stirno** [comment]
Fixed in 318 build..Installer updated.
