### ISSUE TITLE
Issues around about page

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#121]
1. Open scrawl
2. Create new file
3. Open about page
4. Click File/Quit. Nothing happens
5. Close about tab and notice new file has turned to white with red cross
   ![aboutissue](https://cloud.githubusercontent.com/assets/396538/6975848/bf891d86-d999-11e4-8b5b-e5a7ead058ab.gif)

I have seen crashes around trying to close this messed up tab but not consistently

**Comment by stirno** [comment]
I can't make this happen no matter how hard I try. hmm.

**Comment by pauljz** [comment]
@dpen2000 I can't repro this either. Is this still happening at all in newer versions?

**Comment by dpen2000** [comment]
No it doesn't happen for me now.
