### ISSUE TITLE
Files with dependencies upon other files aren't merged properly

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#124]
```
<Content Include="Web.config" />
<Content Include="Web.Debug.config">
    <DependentUpon>Web.config</DependentUpon>
</Content>
<Content Include="Web.Release.config">
    <DependentUpon>Web.config</DependentUpon>
</Content>
```

The above files are dependent upon each other yet Scrawl shows them as separate entities due to the `Content` element.

![image](https://cloud.githubusercontent.com/assets/743025/6987862/c1f07fb2-da00-11e4-906c-c95654ee051a.png)

Other filetypes are not so lucky.

```
<TypeScriptCompile Include="Scripts\definitions.ts" />
    <Content Include="Scripts\definitions.js">
    <DependentUpon>definitions.ts</DependentUpon>
</Content>
```

![image](https://cloud.githubusercontent.com/assets/743025/6987813/61fb2724-da00-11e4-8d15-3f5dd65f5d3c.png)

Only the `definitions.js` file shows up in the project viewer. The `.ts` file is nowhere to be found. 

Where'd my files go?
![giphy](https://cloud.githubusercontent.com/assets/743025/6987867/c71541bc-da00-11e4-9618-21445a87eab5.gif)

**Comment by stirno** [comment]
The joys of csproj.

**Comment by stirno** [comment]
Not entirely happy with the visual we've got atm but I do have this working in dev now. Should merge back so you can see it soon.
