### ISSUE TITLE
Opening large solution causes the UI to hang for a while

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#13]
Opened up a solution with roughly 80 projects. The UI got the normal non-responsive border around it for about 20 seconds before the workspace loaded.

Needs moooorr asynccccccc!

![image](https://cloud.githubusercontent.com/assets/895629/6550144/1026c276-c65c-11e4-8772-f70ceae8b8bf.png)

**Comment by stirno** [comment]
Indeed. was it good after 20 seconds? :)

**Comment by phillip-haydon** [comment]
No issues at all after the 20 seconds. 

Just worried the thing would crash because it was unresponsive.

**Comment by stirno** [comment]
Fixed to run in background thread. We'll make it looking this feel faster ala VS' (loading) bits later but for now it shouldn't block. In #187/
