### ISSUE TITLE
Quitting takes two attempts with open files

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#132]
1. Open scrawl
2. Click File/Quit
3. Scrawl closes immediately
4. Open scrawl
5. Open a file
6. Click File/Quit
7. Scrawl remains open until user picks File/Quit again

![quitingtakestwoattemptswithopenfiles](https://cloud.githubusercontent.com/assets/396538/7011837/63a6ab7e-dca4-11e4-9095-c4b701aa3be9.gif)

**Comment by stirno** [comment]
Unrelated to the bug reported but.. how big is that file?

**Comment by dpen2000** [comment]
19kb (and yeah, that does seem slow to open)

**Comment by stirno** [comment]
Fixed
