### ISSUE TITLE
Opening solution doesn't open workspace explorer

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#133]
Opening a solution or project file used to open workspace explorer: now it doesn't. Can this be reinstated?

**Comment by phillip-haydon** [comment]
![workspace](https://cloud.githubusercontent.com/assets/895629/7106185/e068b320-e16b-11e4-9dea-c13d70ebd624.gif)

**Comment by stirno** [comment]
This is enabled again.
