### ISSUE TITLE
Control-shift-B results in scrawl losing focus

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#136]
![focusissue](https://cloud.githubusercontent.com/assets/396538/7149225/a3bab304-e302-11e4-9eed-e279f7c0ab1d.gif)

Here I press control-shift-B which launches output window but also gives focus to explorer window

**Comment by stirno** [comment]
hmm. i only noticed this once.. but thought it was random. Ok then.

**Comment by dpen2000** [comment]
It seems to happen only when scrawl first opens.

**Comment by stirno** [comment]
Ya its when we launch the msbuild process the first time the new process gets focus. Gonna have to play some games to change that. This bug might survive for awhile.

**Comment by stirno** [comment]
We're in a better place for this where it only happens once. Going to have to leave it like this for awhile. Will reopen when we can take another stab at it.
