### ISSUE TITLE
Task Contextmenu is partially obscured

### ISSUE THREAD

**Issue by bitbonk** [fluentCODE/ScrawlIssues#138]
![image](https://cloud.githubusercontent.com/assets/418030/7201226/2b36708a-e505-11e4-917f-34c54a0cf4c0.png)

**Comment by bitbonk** [comment]
Please note that the window close button in the upper right corner is also invisible.

**Comment by stirno** [comment]
wow.. I mean.. we've had bugs where Scrawl was hard to close but thats a new one.

**Comment by pauljz** [comment]
The issue with the icons blending into the background is fixed in build 395

**Comment by pauljz** [comment]
And fixed the issue with popup height in build 417. 

![screen shot 2015-04-26 at 6 45 26 pm](https://cloud.githubusercontent.com/assets/666213/7339909/9e258e64-ec44-11e4-8959-2a25af64ef00.png)
