### ISSUE TITLE
Tabbing intellisense causes cursor to defocus

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#139]
![losing-cursor](https://cloud.githubusercontent.com/assets/895629/7214127/bae34cde-e5ce-11e4-98db-79a1ac86f17d.gif)

As you can see when I type `M` and it pre-selects `Model` I press the `tab` key, it causes it to defocus (not sure where to) and I have to click in again to continue.

**Comment by stirno** [comment]
Ugh.. async event handling again.

**Comment by stirno** [comment]
Fixed in next build
