### ISSUE TITLE
Dark theme makes top right menu options hide

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#14]
![image](https://cloud.githubusercontent.com/assets/895629/6550169/94fcb46a-c65c-11e4-8e26-2728d6f30424.png)

That's the top right hand corner. 

![image](https://cloud.githubusercontent.com/assets/895629/6550173/a0b68c40-c65c-11e4-8d12-d65f5b2c0a53.png)

:)

**Comment by pauljz** [comment]
This is the default behavior in Win 10 right now, but we'll colorize the icons for dark themes as a short term fix until Windows comes up with a standard solution.

**Comment by pauljz** [comment]
The dark themes will now make those icons white. For some reason this requires an application restart though. I'll leave the issue open until we can make it happen without a restart.

**Comment by phillip-haydon** [comment]
I honestly wouldn't waste time trying to fix the colour without a restart.

Just prompt the user to say that some settings will only take affect after restarting the IDE. And don't worry about the pain of updating the UI elements seemlessly. 

Its a feature people turn on. Restart their IDE. Then never worry about again.

**Comment by pauljz** [comment]
Yeah, not a big deal for just the window chrome, but it's something that would've affected nearly every button in the UI too.

Plus turns out it was a one-line fix! Fixed by https://twitter.com/scrawlcommits/status/574819830899023872
