### ISSUE TITLE
Do you want to save your changes to '' before closing? (issue with task runner)

### ISSUE THREAD

**Issue by aarondandy** [fluentCODE/ScrawlIssues#140]
1) Open directory with a gulp file and some other file(s). In this case I have a gulp file at `./gulpfile.js` .

2) Open a file within the folder. In this case I opened `./build/baufile.csx` .

3) Run a gulp task from the task menu. In this case I ran a task titled `ts-compile` .

4) Close Scrawl

Expected: Scrawl closes

Actual: Scrawl prompts to save a file with no name

```
---------------------------
Save changes?
---------------------------
Do you want to save your changes to '' before closing?
---------------------------
Yes   No   Cancel   
---------------------------
```

**Comment by pauljz** [comment]
The terminal is based on the text editor, and since there was output to it, it thinks it's "dirty" and is prompting you to save the terminal output to a file. Should be able to get this fixed pretty easily.

**Comment by stirno** [comment]
Although interestingly.. you could totally save the output from that window. ;p

**Comment by pauljz** [comment]
Fixed in 416
