### ISSUE TITLE
ctrl+left arrow and ctrl+right arrow move to the next space delimited group not the next token

### ISSUE THREAD

**Issue by bryanwood** [fluentCODE/ScrawlIssues#141]
![Scrawl](http://i.imgur.com/dGZYIsa.gif)

![VS](http://i.imgur.com/UNR6QMV.gif)

**Comment by pauljz** [comment]
Not really a "bug" so much as an unexpected behavior. There are a few different variants on what it means to skip a "word". I'll update this pretty soon to advance by symbol-delimited words instead of whitespace delimited words.

**Comment by stirno** [comment]
Should be noted we'll get closer to the VS behaviors with things like this in the future when we allow CodeEngines to provide the extra context to know what a symbol really is.

The implementation we have right now actually works everywhere so is a bit less intelligent but much more flexible.

**Comment by pauljz** [comment]
This is changed in build 414. The logic goes that it will start by moving forward over whitespace. Once the whitespace ends, the first character it hits determines the character class (either symbols or alphanumeric characters) for continuing the move. It'll then advance forward until it hits something outside the character class. Nice and simple and feels good for most things.

We'll need to go in later and define different rules for symbol heavy languages, but this gets the job done for most common languages.
