### ISSUE TITLE
Windows snapping doesn't work in Windows 8

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#142]
`WIN` + `Left`
`WIN` + `Right`
`WIN` + `Up`
`WIN` + `Down`

None of these work. 

Only `Shift` + `WIN` + `Right` / `Shift` + `WIN` + `Shift`

**Comment by stirno** [comment]
Its true. Windows doesnt think we're a window. We'll get it fixed. Thanks!

**Comment by pauljz** [comment]
Along with alt-tab, this is fixed in 415
