### ISSUE TITLE
Search and Replace issues

### ISSUE THREAD

**Issue by richardprice** [fluentCODE/ScrawlIssues#144]
Currently the search and replace panel vanishes once you carry out the action, which is annoying in itself as you may want to do further actions.

More importantly, the current behaviour when the search and replace panel is hidden the two values are cleared, meaning a user has to re-enter the values if they want to repeat the action.

This has significant workflow issues when you are doing complex regex search and replaces - if you do one and get it wrong, reversing the action is a simple Ctrl-Z, but fixing the regex is then impossible since the values have been cleared, so you have to reenter the entire search and replace values again.

I do a lot of data massaging which requires a lot of regex search and replaces, and this issue with multiple editors (I'm looking at you, Brackets, who even clear the values when you switch tabs...) keeps me going back to EditPlus, which seems to have got this particular feature down perfectly for myself.

Yes, you can copy the two values out to a blank tab before hitting "go" but that kind of defeats the object of having a featured editor :/

**Comment by pauljz** [comment]
Implemented in build 471.

Quick fix for this one - I just made it persist the last values for the find and replace boxes across all files/buffers.

I wonder if it's worth dealing with having separate find/replace persistence for different projects, or different file types? This'll do for now though.
