### ISSUE TITLE
Ctrl + V to paste lines sticks it in between current characters

### ISSUE THREAD

**Issue by xavierzwirtz** [fluentCODE/ScrawlIssues#147]
In visual studio if you Hit `Ctrl + C` in the middle of a line to copy it, followed by `Ctrl + V` it inserts the pasted line before the line your cursor is on. Same for sublime.

In scrawl it copies the line just fine, but instead of inserting it before the current line it inserts it between the characters your cursor is at.

**Comment by pauljz** [comment]
Good catch. Should be a pretty easy fix. I'll take care of this pretty soon, probably once I've got debugging merged to master.

**Comment by pauljz** [comment]
Fixed in 467.

This commit also made it so multi-cursor cut/paste operations will properly multiplex across cursors.
