### ISSUE TITLE
Escape does not remove multi cursors

### ISSUE THREAD

**Issue by xavierzwirtz** [fluentCODE/ScrawlIssues#148]
When you have multiple cursors in sublime, you can hit `Esc` to remove all but the first. Would be nice to have that in scrawl.

**Comment by pauljz** [comment]
I'll get this fixed pretty soon. We had this working in an older build, but when we re-did how keybinds worked we lost it. Oops.

As a short term workaround, you can left click to clear the extra cursors.

**Comment by pauljz** [comment]
Fixed in 470.

When you press Escape, it'll first clear selections if you have any. If you don't have any selections it'll clear all but your first cursor.
