### ISSUE TITLE
scriptcs nuget packages not recognized correctly

### ISSUE THREAD

**Issue by filipw** [fluentCODE/ScrawlIssues#149]
CSX file:

```
using Ionic.Zip;

var foo = new Zip
```

`scriptcs_packages.config`

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="DotNetZip" version="1.9.3" targetFramework="net20" />
  <package id="ScriptCs.Adder" version="0.1.1" targetFramework="net45" />
</packages>
```

Here's a screenshot from Scrawl - not recognizing `DotNetZip`.

![screenshot 2015-05-05 01 04 39](https://cloud.githubusercontent.com/assets/1710369/7464418/38820922-f2c3-11e4-8610-f404b83cc50c.png)

Here is a corresponding one from Visual Studio Code - `DotNetZip` referenced correctly:

![screenshot 2015-05-04 21 55 26](https://cloud.githubusercontent.com/assets/1710369/7464420/4295fffe-f2c3-11e4-85f0-74fa7628bf94.png)

**Comment by stirno** [comment]
Fixed in 442
