### ISSUE TITLE
Workspace explorer doesn't load mvc projects

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#15]
I have a couple mvc projects in a folder and when i double click the sln and it switches to workspace mode the mvc projects are not listed.

**Comment by stirno** [comment]
Via some more conversation.. we've figured out that it does load our MVC projects fine but this one is maybe very large. Might need more info to debug further.

**Comment by stirno** [comment]
We werent setting the VS Version based on the SLN, fixed in 252 and additional fixes in 253 related to this.
