### ISSUE TITLE
Mac OS X: Dark theme not displaying for new file

### ISSUE THREAD

**Issue by joshgerdes** [fluentCODE/ScrawlIssues#159]
v0.1.515

When theme is set to 'dark' or 'darker' and a new file is created the file editor window is displayed in the the default light theme. The tabs are displayed in the selected theme correctly.

**Comment by stirno** [comment]
UI themes and editor themes are separate (and next to each other in settings). Choose a darker editor theme.

**Comment by joshgerdes** [comment]
Sorry, I must have been on crack on this one. Not sure why was mixing that up. But I am seeing some weirdness in the settings panel. I'll log new issues for that those though.
