### ISSUE TITLE
c# parsing producing strange results

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#16]
![image](https://cloud.githubusercontent.com/assets/743025/6550335/440ae8c6-c5e2-11e4-8e96-b8f922bceb7f.png)

**Comment by stirno** [comment]
Related file: https://gist.github.com/Buildstarted/ae36f52c360dd3dd7cef

**Comment by pauljz** [comment]
Fixed in: https://twitter.com/scrawlcommits/status/574807707263320065
