### ISSUE TITLE
Mac OS X: Opening file from file explorer causes status bar text to overlap

### ISSUE THREAD

**Issue by joshgerdes** [fluentCODE/ScrawlIssues#161]
v0.1.515

Opening a file from the file explorer causes status bar text to overlap. Opening new file also causes issue.

![screen shot 2015-05-20 at 3 06 29 pm](https://cloud.githubusercontent.com/assets/145640/7735291/fe31e6e8-ff01-11e4-9cf9-8e9f4d0e6e27.png)

**Comment by pauljz** [comment]
Fixed in build 524
