### ISSUE TITLE
Mac OS X: Settings panel theme list display issue

### ISSUE THREAD

**Issue by joshgerdes** [fluentCODE/ScrawlIssues#164]
v0.1.515 on Mac OS X Yosemite 10.10.3

In the settings panel, for the theme lists each line item is overlapping and not fully displaying the text.

![screen shot 2015-05-20 at 8 29 06 pm](https://cloud.githubusercontent.com/assets/145640/7739915/f80b7ebe-ff2e-11e4-9619-476666074d96.png)

**Comment by pauljz** [comment]
Hacked around in v527. Still an issue if you use extremely large fonts, and a bit awkward if you use extremely small fonts.
