### ISSUE TITLE
Mac OS X: Issue changing font for UI or Editor

### ISSUE THREAD

**Issue by joshgerdes** [fluentCODE/ScrawlIssues#165]
v0.1.515 on Mac OS X Yosemite 10.10.3

Not sure if this is user error, but I am unable to select a new font or font size for UI font or editor font in the settings panel. A font preference panel pops up but I am unable save/set new values when they are selected.

![screen shot 2015-05-20 at 8 41 00 pm](https://cloud.githubusercontent.com/assets/145640/7740034/b4092a0c-ff30-11e4-82de-1c4f266d6ac0.png)

**Comment by pauljz** [comment]
Fixed in 527
