### ISSUE TITLE
Can't add `n` character to .csx file.

### ISSUE THREAD

**Issue by aarondandy** [fluentCODE/ScrawlIssues#166]
1) Open a .csx file.
2) Click in the file to add text in insert mode.
3) Press the `n` key on the keyboard.

Expected: an `n` character has been inserted in the text.
Actual: new file is opened.

**Comment by Buildstarted** [comment]
happens on any new file type as well

**Comment by pauljz** [comment]
Yeah, turns out I bound New File to <kbd>N</kbd> instead of <kbd>Ctrl</kbd><kbd>N</kbd>. Fixed in 529
