### ISSUE TITLE
maximized window cuts off update available notice

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#18]
![image](https://cloud.githubusercontent.com/assets/743025/6550403/342af3f4-c5e4-11e4-9929-851e6db496ea.png)

**Comment by pauljz** [comment]
What DPI and screen resolution are you on?

**Comment by Buildstarted** [comment]
1980x1200 and 100%

**Comment by Buildstarted** [comment]
This only happens if the window is maximized _before_ the update available notice shows up changing window state fixes it afterwards

**Comment by pauljz** [comment]
Fixed in build 213 https://twitter.com/scrawlcommits/status/575512296669184000
