### ISSUE TITLE
Opening solution multiple times appends to workspace explorer

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#20]
Double clicking the same solution multiple times appends to the existing workspace explorer.

![image](https://cloud.githubusercontent.com/assets/743025/6550468/ca53b928-c5e5-11e4-94b2-eaad3ee3ee7e.png)

**Comment by stirno** [comment]
Lord..Lord..Lord.

**Comment by stirno** [comment]
Fixed in build 210.
