### ISSUE TITLE
Autocompleted C# code is invisible

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#25]
1. Go to C# file
2. Start typing "str"
3. Accept completion by pressing tab
   str is visible but ing is different colour (too dark to see):
   ![image](https://cloud.githubusercontent.com/assets/396538/6551651/ceea2e42-c633-11e4-9d80-447d0423c122.png)

**Comment by stirno** [comment]
What you have there is a tab character. The actual bug is that tab isn't triggering completion

**Comment by stirno** [comment]
Tab now triggers autocompletion as of build 183
