### ISSUE TITLE
Ctrl + Arrow should navigate word by word

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#26]
In many editors, you can navigate with "ctrl + left/right arrow" word by word, which is very handy.

**Comment by pauljz** [comment]
Basic implementation is done https://twitter.com/scrawlcommits/status/575020127625830400

Down the road we'll add a few more next word modes you can bind. The variants I can think of are:

1) Emulation of vim's `e` `E` `w` `W` `b` `B` `ge` and `gE` set of commands.
2) Word boundaries defined by CamelCase (suggested by @Buildstarted)
