### ISSUE TITLE
Autocomplete box shows when pressing "Enter" in the middle of a blank line

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#27]
Steps to reproduce:
1. Set the cursor in the middle of a blank line (= a line containing only spaces)
2. Press Enter

An autocomplete box comes to the top of the editor:
![scawl-auto](https://cloud.githubusercontent.com/assets/1180984/6551747/daf4fe1a-c63d-11e4-91f5-cbb171d86c83.PNG)

**Comment by stirno** [comment]
Fixed in a 20x build. Forgot to close.
