### ISSUE TITLE
When using arrow keys, autocompletion doesn't hide or update when you leave the originating symbol

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#29]
1. Start typing something in C# that will result in autocomplete window
2. Press right arrow a few times. Note that autocomplete window moves with current text position even if on a new line: (my text cursor position is just before the ForMember now)
   ![image](https://cloud.githubusercontent.com/assets/396538/6551906/6ea5bd90-c637-11e4-9414-2802dcad1a40.png)
3. Press tab to accept and error appears: (doesn't always happen: seems to be when text position is within c# code)
   ![image](https://cloud.githubusercontent.com/assets/396538/6551805/1c0abc8a-c636-11e4-8787-025aad1afc7c.png)

**Comment by stirno** [comment]
This is because we deploy a debug roslyn build with assert's turned on. they can be safely ignored in these builds. I'll switch to release once we're a bit further along :)

**Comment by yannisgu** [comment]
Yeah but even without this asserts: When you move the cursor with the keys, intelisense is just following the cursor without udpating it, so often the intelisense is completly useless.

**Comment by dpen2000** [comment]
VS behaviour is intellisense disappears when the user presses right arrow key: it does not accept the completion.

**Comment by stirno** [comment]
Ya our intent was to let you navigate within the string via cursors without resetting completion values.. but we do have to deal with when you leave the symbol to hide it or re-request.

**Comment by stirno** [comment]
Implemented a behavior for this in dev
