### ISSUE TITLE
Zoom to quickly increase font-size in editor

### ISSUE THREAD

**Issue by fekberg** [fluentCODE/ScrawlIssues#31]
There's no way of quickly just zooming in to code.

Also, persisting zoom within new files!

**Comment by stirno** [comment]
Implemented a simple mechanism to do this that has lots of little edge cases but solves the early simple use cases of larger text for presentations, etc. easily. Will combine with a proper zoom control and better mechanisms later. Thats in backlog here: https://github.com/fluentCODE/ScrawlBacklog/issues/8

**Comment by luisrudge** [comment]
I think it's awesome the way it is now!
