### ISSUE TITLE
File won't be opened after going to settings 

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#32]
Steps to reproduce:
1. Click on a file in file explorer to open "preview" (not sure how you call it)
2. Open settings
3. Close settings
4. Click again on the file in file explorer

Nothing will happen :( 
However when you click on a file not already opened and then again on the opened file it will work

**Comment by pauljz** [comment]
Fixed by https://twitter.com/scrawlcommits/status/574961801873457152
