### ISSUE TITLE
Random crashes 

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#33]
The integrated  Visual Studio crashing mode is quite good. 

However I know not everybody will like it.

How can we help fixing this. Are there any log which is written?

**Comment by fekberg** [comment]
You could start by explaining what you were doing at the time of the crash, and try to reproduce it again and attach step-by-step instructions. That would most likely help them fix it quicker.

**Comment by stirno** [comment]
Things that actually crash the app should create a few entries in the system event logs accessible via Event Viewer. That data would helpful too. Or if its the kind of error that pops up the 'Debug or Close' box, the text of the little window there would be great.

**Comment by yannisgu** [comment]
Oh system event log... Thx!
