### ISSUE TITLE
Line Height does not scale with font sizes. 

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#35]
![image](https://cloud.githubusercontent.com/assets/895629/6558429/1f18ec5e-c6b7-11e4-82be-5860855bb631.png)

**Comment by stirno** [comment]
Ya.. we deal with that in the editor much better than other UI controls. Most of the controls will fix themselves with a restart of the app after setting the font size.

**Comment by pauljz** [comment]
Fixed in build 219
https://twitter.com/scrawlcommits/status/575548398578851841
