### ISSUE TITLE
Expand close button to corner

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#36]
Typical win7/win8 behavior is that the close button actionable area extends to the corner of the application when in full screen mode even though the UI doesn't show it.

**Comment by pauljz** [comment]
Fixed by https://twitter.com/scrawlcommits/status/575078830391586816 for v0.1.185

**Comment by Buildstarted** [comment]
While this has been fixed the button is now _broken_ in non-full screen mode. But maybe it's my expectations. When in fullscreen mode there's no need for a "border" around the window to resize it with. but in non-fullscreen mode there is. The close button now prevents resizing from that corner when in non-fullscreen mode :)

**Comment by pauljz** [comment]
Oops, missed that comment. That's also fixed now though, in build 235. It's a smaller draggable area than I'd like, but we can't easily fix that without changing the window chrome some more.
