### ISSUE TITLE
Clicking on a .dll or .exe...

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#37]
If you open a folder and there's a .dll or .exe, it shouldn't attempt to open it at all. Should probably warn the user first. Managed to crash the IDE by opening a 25mb .dll file.

**Comment by pauljz** [comment]
Short term we'll fix this by making it so you can't open a handful of known binary types.

Longer term, probably a hex editor, and/or displaying metadata about the binary file you've opened.

**Comment by stirno** [comment]
Short term we'll put a filtered list of files not to attempt to open in place. Its too easy to misclick right now and get in a bad place.

**Comment by stirno** [comment]
Blocked several common binary formats from being opened for now. Will tackle later in specific support for new formats (hex editor, images, etc)
