### ISSUE TITLE
"Home" should go to the first character, not to the start of the line

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#41]
Currently when pressing `Home` the cursor moves to the start of the line. Better would be, if the cursor moves to the start of the code on the line. So basically before the first non-space character.

**Comment by Buildstarted** [comment]
alternatively it could follow vs rules and to to the start of the line if already on the first non-whitespace character

**Comment by pauljz** [comment]
We'll implement this as:
- On any character other than the first non-whitespace character, move to the first non-whitespace character
- On the first non-whitespace character, move to the start of the line.

This is consistent with what most editors are doing now.

**Comment by pauljz** [comment]
Implemented by https://twitter.com/scrawlcommits/status/575027985683775489

Build 0.1.182
