### ISSUE TITLE
"last comes before first" exception from roslyn

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#42]
Steps to reproduce:
1. New console application
2. In the `Main` method type `(`, a `)` will be inserted by Scrawl
3. Move with the right arrow to the end of the line
4. Delete the `)` with backspace

This produces the following exception:
![scawl-roslyn](https://cloud.githubusercontent.com/assets/1180984/6562319/55ea48fa-c698-11e4-9f02-55ff9e2436ce.PNG)

**Comment by stirno** [comment]
I believe this was related to a previous issue where Roslyn was not being kept up to date properly. Thats been fixed and I can no longer repro this issue. Closing.
