### ISSUE TITLE
Scrawl.exe should open the file specified with command line args

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#44]
If one passes a command line argument to Scawl.exe, this arg should be treated as file or folder to open. 

AFAIK this also adds support for "Open with.." from Windows Explorer.

**Comment by stirno** [comment]
Agreed. We talked about getting this in before we pushed the CI build yesterday but went ahead without it. Will do soon.

**Comment by yannisgu** [comment]
:+1:

**Comment by stirno** [comment]
You can now use:

```
scr .
scr file.cs
scr Project\

scrawl .
scrawl file.cs
scrawl Project\
```

as of build 239.

Adding Scrawl to the various Open With menus will be handled later via https://github.com/fluentCODE/ScrawlBacklog/issues/7

**Comment by luisrudge** [comment]
:heart:

**Comment by luisrudge** [comment]
```
λ scrawl .
'scrawl' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by luisrudge** [comment]
@stirno thoughts?

**Comment by luisrudge** [comment]
ok. I had to reopen the cmd line

**Comment by stirno** [comment]
ya, any changes to PATH require the command line to be reopened
