### ISSUE TITLE
tab name is barely readable when hovering

### ISSUE THREAD

**Issue by luisrudge** [fluentCODE/ScrawlIssues#45]
![image](https://cloud.githubusercontent.com/assets/941075/6568051/1b4473c0-c6b0-11e4-8596-53ccc28c1756.png)

**Comment by pauljz** [comment]
I think the underlying issue here is when you increase the font size, a bunch of UI elements don't resize properly. Similar issues happen with the Folder Explorer/Workspace Explorer not adjusting their line heights.

Probably the same as #35

**Comment by pauljz** [comment]
Fixed in build 219
https://twitter.com/scrawlcommits/status/575548398578851841
