### ISSUE TITLE
shift+del should cut the entire line to clipboard

### ISSUE THREAD

**Issue by luisrudge** [fluentCODE/ScrawlIssues#49]

**Comment by pauljz** [comment]
Will implement this a bit later on. Going to also do a vim `d` deletion buffer where as you keep deleting more, it keeps appending to the clipboard.

**Comment by luisrudge** [comment]
Shift del looks pretty basic editor behavior. The vim stuff can wait :D

Enviado pelo meu Windows Phone

**Comment by pauljz** [comment]
Okay, okay, fine. :p

Implemented in v0.1.190 https://twitter.com/scrawlcommits/status/575130973228105728

**Comment by luisrudge** [comment]
:heart:
