### ISSUE TITLE
Activation Screen doesn't display correctly

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#5]
Windows 8.1. 

![image](https://cloud.githubusercontent.com/assets/895629/6549951/c1c9da7c-c657-11e4-918e-05dcfebebb98.png)

**Comment by stirno** [comment]
Whats your monitor resolution and DPI settings?

**Comment by phillip-haydon** [comment]
1920x1080
Running on HDMI

![image](https://cloud.githubusercontent.com/assets/895629/6549968/2fb67900-c658-11e4-8e00-ce607ae69860.png)

![image](https://cloud.githubusercontent.com/assets/895629/6549969/34d67dd6-c658-11e4-8c9d-9cde82efab5a.png)

**Comment by pauljz** [comment]
Fixed in build 218 https://twitter.com/scrawlcommits/status/575539617283379200
