### ISSUE TITLE
Deleting multiple lines seem to not work correctly

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#51]
I am quite sure that there is something teribly broken with deleting multiple characters. 
GIven this code:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScawlTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hey");
        }
    }
}

```

... select `Hey");` and press `Backspace`.
For me this will result to:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScawlTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("
        }
    }
}  }
}
```

Note that this is not reproducible with the `Delete` key.

**Comment by stirno** [comment]
Hmm..
![deletinghey](https://cloud.githubusercontent.com/assets/666175/6577612/43ae8168-c70d-11e4-937f-30f49b81f881.gif)

**Comment by yannisgu** [comment]
Hmm, and if you look at the file in a stable editor ;) ?

**Comment by pauljz** [comment]
Fixed in build 204
https://twitter.com/scrawlcommits/status/575395025250578433
