### ISSUE TITLE
Better windows icon

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#57]
Because the current one sucks even tho the Icon for the task bar is nice... 

Taskbar Icon = The Awesome
Desktop Icon = The Suckz

**Comment by pauljz** [comment]
These should be pretty everywhere now (but you may need a reinstall for the desktop icon, not sure?). @stirno fixed this a few builds back.

![screen shot 2015-04-26 at 6 52 27 pm](https://cloud.githubusercontent.com/assets/666213/7339924/6daa1376-ec45-11e4-86cf-72dde31e1a1b.png)
