### ISSUE TITLE
When updating, if there's no updates, should tell me.

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#58]
It's hard to know sometimes when Scrawl is doing something or not. Right now it would be nice to know if there are no updates.

The popup that says "update" if that said "no updates" for a few seconds then disappeared. That would be awesomesauce.

**Comment by stirno** [comment]
Added a 'Checking for Updates' deal when it starts looking and if none are available, for 5 seconds you'll have a 'No Updates' box in the same place. can be clicked to dismiss earlier. In build 195.
