### ISSUE TITLE
Tab Text is too small that it's blurry on my screen

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#6]
Not sure how this will look when you view the screenshot.

![image](https://cloud.githubusercontent.com/assets/895629/6550005/d48b1ba2-c658-11e4-820d-dc95a3a7209c.png)

The main navigation is nice and sharp.

The 'File Explorer' and tab text are very small.

![image](https://cloud.githubusercontent.com/assets/895629/6550011/eaae2578-c658-11e4-8669-f12bd124afd5.png)

Infact I think by default the font-size should be larger.

**Comment by pauljz** [comment]
We'll take a look at bumping up the default font sizes.

**Comment by stirno** [comment]
Changed in dev.
