### ISSUE TITLE
No autocomplete in new console app

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#62]
1. Create a console app in VS
2. Open solution in Scrawl
3. Typing args. in Main method does not result in intellisense

**Comment by dpen2000** [comment]
Also if I create a .cs file with:

```
public class Bar
{
    public void Foo()
    {
        this.
    }

    public void Test()
    {

    }
}
```

I get no intellisense after this.

**Comment by stirno** [comment]
Second issue fixed in 199, first in 200.

**Comment by dpen2000** [comment]
The console app issue fixed for me after 201 (but not all the time).

**Comment by dpen2000** [comment]
Second issue is fixed but only when I press control-space as far as I've seen so far
