### ISSUE TITLE
Scrawl adds braces to C# file on save

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#65]
In Build 201. If I save a file like:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication15
{
    class Program
    {
        static void Main(string[] args)
        {

        }
    }
}
```

When I reopen it, it has saved as:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication15
{
    class Program
    {
        static void Main(string[] args)
        {

        }
    }
}   }
}
```

Note the additional braces

**Comment by pauljz** [comment]
Are the braces there if you open it up in another editor? Making sure it's an issue with save, not just a rendering blip.

**Comment by dpen2000** [comment]
Yeah I have file open in notepad++ too

**Comment by dpen2000** [comment]
I created a new console app with VS to see if I could repro this on new set of files. Didn't happen if I saved the Program.cs with extra whitespace or adding a statement from Main but removing statement and saving resulted in extra characters being added.
The statement was 

```
args.GetValue();
```

On removing this and saving these characters were added to end of file:

```
e();
        }
    }
}
```

**Comment by pauljz** [comment]
Fixed in build 204
https://twitter.com/scrawlcommits/status/575395025250578433

**Comment by dpen2000** [comment]
LGTM thanks

**Comment by yannisgu** [comment]
:+1:  :+1: now we can actually start to write code with Scrawl :laughing:
