### ISSUE TITLE
Better handling of intelisense of methods

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#68]
When pressing enter, when a method is selected in the intelisense, Scrawl should insert `()` after the method, since in 99.9% of the cases this is the thing you want when using a method.

The other way arround when a method is selected in the intelisense und you press `(` it should apply the method from intelisense.

**Comment by stirno** [comment]
Autocomplete basically doesn't deal with methods at all right now, ya. Definitely needed soon.

**Comment by stirno** [comment]
![functionsnippetcompletion](https://cloud.githubusercontent.com/assets/666175/6653977/52dbbdac-ca75-11e4-966f-6caaf1a5914c.gif)
