### ISSUE TITLE
Closing Scrawl and re-opening causes shortcut problem

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#7]
![image](https://cloud.githubusercontent.com/assets/895629/6550034/7378da60-c659-11e4-9a03-29cc38c8e230.png)

Changed some settings. Closed Scrawl. Re-opened. Got this message. Now cannot run Scrawl at all anymore :(

**Comment by bryanwood** [comment]
Had this happen also

**Comment by stirno** [comment]
... wat. Can one of you screenshot AppData\Local\Scrawl folder for me?

**Comment by phillip-haydon** [comment]
![image](https://cloud.githubusercontent.com/assets/895629/6550062/1bcaea14-c65a-11e4-921c-9db0da2f2cec.png)

**Comment by stirno** [comment]
Temp fix for this.. go find your shortcut and update its path to be like:

C:\Users<user>\AppData\Local\Scrawl\Update.exe

where <user> is your user account.

Gotta figure out why squirrel dislikes you guys.

**Comment by stirno** [comment]
Looks like the squirrel boys have it fixed in squirrel/squirrel.windows#269 .. We'll fix soon too.

**Comment by stirno** [comment]
Should be fixed with the new installer here:  https://scrawlci.blob.core.windows.net/installers/scrawl-setup-ci.exe

An update to squirrel was pushed in 232 to fix this potentially happening for users with installs in place already.
