### ISSUE TITLE
Strange intellisense when starting typing the method arguments

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#70]
Let's say I type `Console.WriteLine(`. When intellisense is then started (this happens here sometimes), it proposes `as` or `is`, which is quite strange. As soon as you type any letter, the propositions turns right with all classes and members.

**Comment by stirno** [comment]
This will be resolved with #68 I think. Closing for now.

**Comment by dpen2000** [comment]
This should be reopened: You can clearly see as and is appear in the video attached to #93
