### ISSUE TITLE
Clicking in whitespace *below* the last line of the file

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#73]
Having a file open and clicking in the area below the last line of the file does not set focus to the last character of the file. This is especially noticeable if the cursor is beyond the visible area of the editor.

To reproduce just open a file set the cursor at the first character, scroll so that the cursor is off screen and the area beyond the last line is visible and click in that area.

**Comment by pauljz** [comment]
Fixed in build 221 https://twitter.com/scrawlcommits/status/575799449840140288
