### ISSUE TITLE
Cursor does not come into view when typing

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#74]
If the cursor location is not visible in the current editor and you start typing you cannot see the resulting text. When you start typing and the cursor is not in the current view it should scroll to the cursor or ensure that the cursor is visible.

**Comment by pauljz** [comment]
You're not seeing this kind of behavior? Using multiple cursors or any shenanigans like that?

![2015-03-11_17-36-26](https://cloud.githubusercontent.com/assets/666213/6608512/884e8b48-c815-11e4-9e3a-5287f512416e.gif)

**Comment by Buildstarted** [comment]
![cursor](https://cloud.githubusercontent.com/assets/743025/6608570/41298f7a-c805-11e4-803d-2202e46a8f25.gif)

**Comment by pauljz** [comment]
Oh, huh, only happens for me when you scroll all the way to the bottom, but I can definitely reproduce this.

Hooray for gifs!

**Comment by pauljz** [comment]
Fixed in build 220 https://twitter.com/scrawlcommits/status/575792336099237891
