### ISSUE TITLE
Resizing window doesn't scale the open windows appropriately

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#75]
having multiple windows open and resizing the window causes the lower or far right windows to get really small when changing the window size smaller.

Possibly expect the windows size to scale.

![image](https://cloud.githubusercontent.com/assets/743025/6607585/396d4522-c7fd-11e4-97ee-35699b8cbf4e.png)

**Comment by Buildstarted** [comment]
Seems to only happen when there are multiple windows in a section. i tried it with one window on top and on bottom and one window left/right and they scale properly

**Comment by pauljz** [comment]
I think this is probably something where the UI just needs to be clearer about what's going on.

There are two different ways we deal with splits. You can have a percentile split (vertical/horizontal), or a fixed split (top/right/bottom/left) that stays at certain number of pixels. Right now the two aren't clearly differentiated in the UI (see below).

I think if we make the UI clearer about what it's doing that'll help. I'll think about the UX for this. Maybe having a `|-------- 100px --------|` or a `|-------- 50% --------|` in the rubber band area would be enough.

Here's how we show a percentile split:
![scrawl-split-vertical](https://cloud.githubusercontent.com/assets/666213/6607911/b025d612-c810-11e4-938a-46a7f2b8ce24.png)

And here's a fixed split:
![scrawl-split-right](https://cloud.githubusercontent.com/assets/666213/6607912/b025e8aa-c810-11e4-87e9-e3632c595575.png)

**Comment by Buildstarted** [comment]
Yes, that explains it perfectly. No issue then

**Comment by pauljz** [comment]
Still a bit of a UX problem here, but I've got a sticky note written down to address it.
