### ISSUE TITLE
Double clicking an already open file doesn't bring the file into focus

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#76]
When a window is already open and you double-click the file in explorer/workspace it doesn't bring the window into focus (or change to the correct tab)

**Comment by pauljz** [comment]
This should be fixed in 223 as well, if it's the issue I think it is. I was never able to reliably reproduce this one myself. https://twitter.com/scrawlcommits/status/575880279816040448
