### ISSUE TITLE
Strange windowing behavior

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#77]
I came across some strange windowing behavior that can only be explained via gif

![strange-windowing](https://cloud.githubusercontent.com/assets/743025/6607831/2a222dec-c7ff-11e4-856d-dcbabdaaac52.gif)

**Comment by pauljz** [comment]
This is a bug I've known about for a while where the size that the rubber band controls use is out of sync with the actual size of the layout items.

**Comment by pauljz** [comment]
Fixed in build 222 https://twitter.com/scrawlcommits/status/575806012919312384
