### ISSUE TITLE
Intellisense doesn't trigger sometimes even when file is fine

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#78]
![nointellisense](https://cloud.githubusercontent.com/assets/396538/6608278/89a96d46-c83d-11e4-855a-ae27fef5bc4f.gif)

**Comment by stirno** [comment]
Found a pretty fun issue with it.. Should feel a _lot_ better in build 246 (in CI now).

**Comment by stirno** [comment]
![newconsoleappautocomplete](https://cloud.githubusercontent.com/assets/666175/6649721/e76d6cba-c9bf-11e4-973b-9d810ef5c278.gif)

**Comment by dpen2000** [comment]
Thanks. Works much better now
