### ISSUE TITLE
Can't make any window take up the first 50% of an area

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#79]
Can't make a window snap to the first 50% of a windowing area.

![more-windowing](https://cloud.githubusercontent.com/assets/743025/6608337/52ab745e-c803-11e4-8bcd-74053e917b5c.gif)

**Comment by pauljz** [comment]
Yeah, I made it so percentile splits are always to the right or bottom, but I guess there's no good reason to limit it that way. Shouldn't be too big a deal to implement this.

**Comment by pauljz** [comment]
Implemented in build 224 https://twitter.com/scrawlcommits/status/575914291972468736
