### ISSUE TITLE
Changing font-size for UI reverts to light theme

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#8]
When changing the UI Font the UI Theme reverts to `light`.

**Comment by stirno** [comment]
hmm. The revert to light behavior generally means it tried to load a theme and failed. Haven't seen it happen with font changes. What font were you switching to?

**Comment by Buildstarted** [comment]
The revert happens to whatever the theme was when scrawl was started. Restarting scrawl now causes the revert to darker theme since that was the theme i started with. Seems that changing font also removes other changes settings such as whitespace and spaces per tab

**Comment by stirno** [comment]
Can you still make this happen on latest? I can't.

**Comment by Buildstarted** [comment]
Yes, it still happens. Do you need a gif?

![font-size-color](https://cloud.githubusercontent.com/assets/743025/6654910/c2c17bcc-caa0-11e4-986c-b09871da4520.gif)

**Comment by stirno** [comment]
Finally repro'd and got it fixed in our dev branch. Stupid bug.
