### ISSUE TITLE
Second newline after braces is tabbed incorrectly

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#80]
![secondnewlineafterclosebrace](https://cloud.githubusercontent.com/assets/396538/6608366/38822f38-c83e-11e4-8f04-ad64a052b173.gif)

Here I'm wanting to create a second method in the class but second newline places my cursor an extra tab in.

**Comment by pauljz** [comment]
Eventually we're going to do a pretty big overhaul of whitespace insertion to make it smarter. In the meantime I think I can do a quick fix for this.

**Comment by pauljz** [comment]
Fixed in build 237 https://twitter.com/scrawlcommits/status/576196023703465986
