### ISSUE TITLE
Strange window placement/focus when putting files in fileexplorers area

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#81]
I don't even know how to explain it - and closing the resulting windows eventually crashes scrawl.

![and-even-more](https://cloud.githubusercontent.com/assets/743025/6609336/575bd0a2-c80d-11e4-858a-ce882df10e77.gif)

**Comment by pauljz** [comment]
Should be fixed in build 223 https://twitter.com/scrawlcommits/status/575880279816040448

**Comment by Buildstarted** [comment]
Here's a quick screenshot showing the new tab on the left that shows up.

![image](https://cloud.githubusercontent.com/assets/743025/6612666/b73d16cc-c83d-11e4-9f2d-de0ee96ac1ee.png)

**Comment by pauljz** [comment]
Sounds like neither of us can repro this one anymore, whereas I consistently could in <.223. Let's call it fixed for now, but I'll keep a close eye on the layout/tabs stuff in general.
