### ISSUE TITLE
opening a lot of files

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#82]
Should probably add a drop down to select more windows on the far right of the tabs.

![image](https://cloud.githubusercontent.com/assets/743025/6624473/bcbc480c-c8a6-11e4-8d3b-aaf643a77f29.png)

I have about 20 files open in this screenshot

**Comment by pauljz** [comment]
Obviously pretty important for real usage. Going to tackle this one pretty soon.

**Comment by stirno** [comment]
We've had this on our wall of post-it notes for a bit. just haven't gotten to it :+1:

**Comment by pauljz** [comment]
Added a dropdown for this in build 254 https://twitter.com/scrawlcommits/status/576828374426996736

There's still some weird behaviors because we don't have a way to scroll the tabs or bring the active one visibly onto the toolbar, but I'll address that soon.

**Comment by pauljz** [comment]
Made it so the active tab is always visible too. This should be enough for now, to at least make things accessible. I've got sticky notes jotted down for the ability to scroll left and right, and the ability to drag and drop to re-order tabs.
