### ISSUE TITLE
Empty window

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#83]
When dragging the only tab out of a window it leaves the window empty of all controls (including menu)

![image](https://cloud.githubusercontent.com/assets/743025/6629694/33649244-c8ce-11e4-86ce-7c310489e14e.png)

![omg-lol-cat-o](https://cloud.githubusercontent.com/assets/743025/6629747/adcc5058-c8ce-11e4-999c-745059680f9b.gif)

**Comment by stirno** [comment]
@pauljz is on the case

![8dgtpaq](https://cloud.githubusercontent.com/assets/666175/6629905/e9277058-c8e0-11e4-82f0-37b58b318111.gif)

**Comment by pauljz** [comment]
Fixed in build 236 https://twitter.com/scrawlcommits/status/576167729813725184

(Aww, now I feel bad for not including a gif of it working properly in the response.)

**Comment by Buildstarted** [comment]
At least include a cat/dog gif of success
