### ISSUE TITLE
scrawl crashes when attempting to view a folder one does not have access to

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#84]

**Comment by pauljz** [comment]
This _should_ be fixed as of build 259. I couldn't actually get my dev copy to crash when opening a folder I didn't have access to (it just failed to open it silently), but did encounter some special folders (e.g. Documents/My Videos) that caused a crash, and those are fixed.

If you see it again, let me know if you were opening it via the folder explorer, or just the file/directory open dialog

**Comment by Buildstarted** [comment]
I was using both. Nice little error message shows up now so I think we're good.
