### ISSUE TITLE
ctrl + arrow is moving to the end of an html tag

### ISSUE THREAD

**Issue by luisrudge** [fluentCODE/ScrawlIssues#85]
![ctrl](https://cloud.githubusercontent.com/assets/941075/6650106/b25c57e6-c9df-11e4-83ed-258d7c91be3f.gif)

**Comment by pauljz** [comment]
Yeah, for now word boundaries are just defined by whitespace. I've added a backlog issue to do a few more variants of this. fluentCODE/ScrawlBacklog#11
