### ISSUE TITLE
ctrl backspace doesn't remove word by word

### ISSUE THREAD

**Issue by luisrudge** [fluentCODE/ScrawlIssues#86]

**Comment by aarondandy** [comment]
This also marks the file dirty without making any changes. This may be a sign of a bug as well.

**Comment by pauljz** [comment]
This is implemented in build 414. Ctrl-Backspace and Ctrl-Delete will delete consistently with the behavior of Ctrl-Left and Ctrl-Right.

On a largely unrelated but useful note, Shift-Delete and Shift-Backspace both now function identically to Delete and Backspace. Previously they just didn't do anything, which was annoying and inconsistent with other editing experiences.
