### ISSUE TITLE
ctrl arrow doesn't stop at special characters

### ISSUE THREAD

**Issue by luisrudge** [fluentCODE/ScrawlIssues#88]
It should stop at the dot

![ctrl](https://cloud.githubusercontent.com/assets/941075/6650115/3df34e36-c9e0-11e4-948d-0395899d9294.gif)

**Comment by pauljz** [comment]
Yeah, same issue as #85. We only use whitespace as a word boundary. Will address with this backlog entry: fluentCODE/ScrawlBacklog#11
