### ISSUE TITLE
Dark theme menus do not show up

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#9]
When using dark theme menus are practically invisible

![image](https://cloud.githubusercontent.com/assets/743025/6550074/cb928804-c5dc-11e4-89c2-54864ba218a3.png)

**Comment by Buildstarted** [comment]
![image](https://cloud.githubusercontent.com/assets/743025/6550085/fbedd602-c5dc-11e4-96d3-a9c064623bfc.png)

**Comment by Buildstarted** [comment]
Restarting scrawl fixed the font coloring

**Comment by stirno** [comment]
Fixed in build #187
