### ISSUE TITLE
Files replace workspace explorer after settings changed

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#91]
![filesopenningwrongpaneaftersettings](https://cloud.githubusercontent.com/assets/396538/6654389/f99d494c-cab8-11e4-9a31-45c72ae2d7d1.gif)

I expected the file to open in the right pane.

**Comment by pauljz** [comment]
Fixed in build 262 https://twitter.com/scrawlcommits/status/576931155464835072
