### ISSUE TITLE
Activating, over, and over, and over...

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#94]
If I activate then not use Scrawl for like 2 days, the next time I open it I have to activate again.

Annoying ><

**Comment by pauljz** [comment]
This should just be checking against the activation server, not actually prompting to enter a license.

**Comment by stirno** [comment]
Its the verification due to length of time since it was last able to verify with the server. If theres been more than 3 days since it last 'checked in', it asks the server if the key is still valid. Server says no if its been longer than a week.

**Comment by stirno** [comment]
I've changed how we decide when to deactivate a license.. You should no longer encounter this behavior as long as your license isn't being shared around.
