### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#96]
Needz codes foldings!

**Comment by pauljz** [comment]
Hmm, should be implemented. What kind of file are you looking at that doesn't have it?

**Comment by phillip-haydon** [comment]
JavaScript file, and LESS file, and CSS file.

**Comment by stirno** [comment]
@pauljz implemented code folding in a way that should work regardless of language support from the tmLanguage file now. Confirmed works with the 3 mentioned formats in dev build.
