### ISSUE TITLE
LESS Syntax Highlighting. 

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#97]
Don't care for intellisense support right now but highlighting would be the beez kneez.

**Comment by pauljz** [comment]
Added LESS and Sass highlighting into our dev branch. Should hit the master CI builds in a few days.

![screen shot 2015-03-28 at 12 03 40 pm](https://cloud.githubusercontent.com/assets/666213/6882122/74ba7056-d549-11e4-85fd-5f73b18307c4.png)
