### ISSUE TITLE
Open Files dropdown icon

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#98]
Pleaseeeee get a normal resolution monitor so you can see all these display errors :)

![image](https://cloud.githubusercontent.com/assets/895629/6881714/68587972-d5a6-11e4-9abc-c7bab04c2c14.png)

This icon looks squashed and messed up.

**Comment by pauljz** [comment]
Yikes, that looks horrible.

**Comment by pauljz** [comment]
Fixed in build 351 https://twitter.com/scrawlcommits/status/587114607405326337

Before and after:

![alpha-compositing-fix](https://cloud.githubusercontent.com/assets/666213/7104698/5b64d7b6-e0b8-11e4-87bd-3d26b1496d95.png)

**Comment by phillip-haydon** [comment]
Updated. Looks good. But cannot open solution files now :(

**Comment by stirno** [comment]
are you sure about that? seems more likely you've just never had to open the Workspace Explorer before. ;p

**Comment by phillip-haydon** [comment]
I worked it out. It's just another bug :)
